spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hireflow}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # Managed by Flyway later
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    baseline-on-migrate: true   # ✅ FIX ADDED

server:
  port: ${PORT:8080}
  error:
    include-message: always

security:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: 86400000

resend:
  api:
    key: ${RESEND_API_KEY:re_cwk6BuMZ_L4BR27Cyc1hmBMyLV1e3fwMH}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:demo}
  api-key: ${CLOUDINARY_API_KEY:key}
  api-secret: ${CLOUDINARY_API_SECRET:secret}

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG

